### PR TITLE
fix: Alter table issue

### LINKED ISSUE #22: ALTER TABLE crashes the server
The alter table command fails and crashed the server.

```sql
alter table testtable add column field3 dec(3,0);                 
ERROR 2013 (HY000): Lost connection to MySQL server during query

alter table testtable modify column field2 dec(5,0);            
ERROR 2013 (HY000): Lost connection to MySQL server during query

alter table testtable drop column field2;                          
ERROR 2013 (HY000): Lost connection to MySQL server during query     
```

### PR DESCRIPTION
**Pull request by abmusse**
Fixes #22 

Turns out that custom min and max macros here were buggy.

https://github.com/zendtech/db2iengine/blob/7339d247bded29f376d1b9a8411caffd7e0ece82/db2i_global.h#L77-L78

In this situation `min` it returned a very large value that got passed into `memcpy` as `num_bytes` causing the failure.

https://github.com/zendtech/db2iengine/blob/7339d247bded29f376d1b9a8411caffd7e0ece82/db2i_file.cc#L380

In this PR we remove using the min and max macros and instead use std::min and std::max.
This also required casting some variables to the appropriate types to work with std::min and std::max.

CC @kadler

### CODE REVIEW

File: db2i_file.cc [hunk 1]
```diff
@@ -376,9 +376,9 @@ void db2i_table::filenameToTablename(const char* in, char* out, size_t outlen)
     if (!part4)
       part4 = strend(in);
   }
-  
-  memcpy(temp, part1, min(outlen, part2 - part1));
-  temp[min(outlen-1, part2-part1)] = 0;
+  size_t num_bytes = std::min(outlen, static_cast<size_t>(part2 - part1));
+  memcpy(temp, part1, std::min(outlen, static_cast<size_t>(part2 - part1)));
+  temp[std::min(outlen-1, static_cast<size_t>(part2-part1))] = 0;
```
Comment (kadler) [inline db2i_file.cc]: Looks like these should use num_bytes, no?

File: db2i_file.cc [hunk 2]
```diff
@@ -387,9 +387,9 @@ void db2i_table::filenameToTablename(const char* in, char* out, size_t outlen)
     strcat(out, "#P#");
     accumLen += 4;
     
-    memset(temp, 0, min(outlen, part2-part1));
-    memcpy(temp, part3, min(outlen, part4-part3));
-    temp[min(outlen-1, part4-part3)] = 0;
+    memset(temp, 0, std::min(outlen, static_cast<size_t>(part2-part1)));
+    memcpy(temp, part3, std::min(outlen, static_cast<size_t>(part4-part3)));
+    temp[std::min(static_cast<size_t>(outlen-1), static_cast<size_t>(part4-part3))] = 0;
```
Comment (kadler) [inline db2i_file.cc]: I think a temp variable would be useful here. Also, looks like maybe the original code had a bug since the memset references part1 and part2, but the other two lines use part3 and part4.

File: db2i_misc.cc [hunk 3]
```diff
@@ -100,7 +100,7 @@ EXTERN bool convertMySQLNameToDB2Name(const char* input,
   
   if (delimit)
     output[o++] = '"';
-  output[min(o, outlen-1)] = 0; // This isn't the most user-friendly way to handle overflows,
+  output[std::min( static_cast<size_t>(o), outlen-1)] = 0; // This isn't the most user-friendly way to handle overflows,
```
Comment (kadler) [inline db2i_misc.cc]: I would probably change `uint o` to `size_t o` instead of the static_cast.

File: ha_ibmdb2i.cc [hunk 4]
```diff
@@ -2791,10 +2791,9 @@ int ha_ibmdb2i::prepReadBuffer(ha_rows rowsToRead, const db2i_file* file, char i
     forceSingleRowRead = true;
     rowsToRead = 1;
   }
+  rowsToRead = std::min(stats.records+1,std::min(rowsToRead, static_cast<ha_rows>(DEFAULT_MAX_ROWS_TO_BUFFER)));
```
Comment (kadler) [inline ha_ibmdb2i.cc]: With the change of `DEFAULT_MAX_ROWS_TO_BUFFER` to an `ha_rows`, this static_cast should be unnecessary.

File: ha_ibmdb2i.cc [hunk 5]
```diff
@@ -2916,8 +2915,8 @@ int ha_ibmdb2i::flushWrite(FILE_HANDLE fileHandle, uchar* buf )
       else
       {
         char unknownIndex[MAX_DB2_FILENAME_LENGTH+1];
-        convFromEbcdic(lastDupKeyNamePtr, unknownIndex, min(lastDupKeyNameLen, MAX_DB2_FILENAME_LENGTH));
-        unknownIndex[min(lastDupKeyNameLen, MAX_DB2_FILENAME_LENGTH)] = 0;        
+        convFromEbcdic(lastDupKeyNamePtr, unknownIndex, std::min(lastDupKeyNameLen, static_cast<uint32>(MAX_DB2_FILENAME_LENGTH)));
+        unknownIndex[std::min(lastDupKeyNameLen, static_cast<uint32>(MAX_DB2_FILENAME_LENGTH))] = 0;
```
Comment (kadler) [inline ha_ibmdb2i.cc:2919]: MAX_DB2_FILENAME_LENGTH should probably be a size_t and likely lastDupKeyNameLen too, but this seems fine for now.

File: db2i_file.cc (hunk 1 above)
Comment (abmusse) [reply db2i_file.cc]: yes. Thanks for catching that

File: ha_ibmdb2i.cc (hunk 4 above)
Comment (abmusse) [reply ha_ibmdb2i.cc]: Yes fixed this to remove the unnecessary cast 

https://github.com/zendtech/db2iengine/pull/23/files#diff-e0e69605b45f256c19b7588c8c2d3d9b30bed1f1cd54f6fd742807a4d51e61e3R2794

File: db2i_misc.cc (hunk 3 above)
Comment (abmusse) [reply db2i_misc.cc]: Changed this to `size_t o`

https://github.com/zendtech/db2iengine/pull/23/files#diff-aa454e414a26f204ea0e1edcc31dbc9714afe333766b3d2388e6af82a41e01f0R85

File: db2i_file.cc (hunk 2 above)
Comment (abmusse) [reply db2i_file.cc]: Created temp varialble of `num_bytes2` to store `static_cast<size_t>(part4-part3)`
Yes looks like bug as they memset  with `num_bytes` of `part2-part1` and later memcpy with `num_bytes` of `part4-part3`

Comment (kadler) [reply db2i_file.cc]: I'm not 100% certain it is a bug, since why would you need to memset if you're going to memcpy over the same amount of data? Of course, it could just be _overly_ defensive code.

File: db2i_file.cc [hunk 6]
```diff
@@ -376,9 +376,9 @@ void db2i_table::filenameToTablename(const char* in, char* out, size_t outlen)
     if (!part4)
       part4 = strend(in);
   }
-  
-  memcpy(temp, part1, min(outlen, part2 - part1));
-  temp[min(outlen-1, part2-part1)] = 0;
+  size_t num_bytes = std::min(outlen, static_cast<size_t>(part2 - part1));
+  memcpy(temp, part1, std::min(outlen, num_bytes));
+  temp[std::min(outlen-1, num_bytes)] = 0;
```
Comment (kadler) [inline db2i_file.cc]:
```suggestion
  size_t num_bytes = std::min(outlen-1, static_cast<size_t>(part2 - part1));
  memcpy(temp, part1, num_bytes);
  temp[num_bytes] = 0;
```

In the memcpy line, outlen has already been used to initialize num_bytes, no need to min against it again. In fact, once the min has been set there's no need to do any further calculations. The only change needed is to reserve one byte from the buffer length for the null terminator.

File: ha_ibmdb2i.cc [hunk 7]
```diff
@@ -3578,8 +3577,9 @@ void ha_ibmdb2i::setIndexReadEstimate(uint index, ha_rows rows)
 
 ha_rows ha_ibmdb2i::getIndexReadEstimate(uint index)
 {
+  ha_rows i = 1;
   if (indexReadSizeEstimates)
-    return max(indexReadSizeEstimates[index], 1);
+    return std::max(indexReadSizeEstimates[index], i);
```
Comment (kadler) [inline ha_ibmdb2i.cc]:
```suggestion
    return std::max(indexReadSizeEstimates[index], ha_rows{1});
```

Don't need the extraneous variable definition, without having the verbose static_cast syntax

File: db2i_file.cc [hunk 8]
```diff
@@ -387,9 +387,10 @@ void db2i_table::filenameToTablename(const char* in, char* out, size_t outlen)
     strcat(out, "#P#");
     accumLen += 4;
     
-    memset(temp, 0, min(outlen, part2-part1));
-    memcpy(temp, part3, min(outlen, part4-part3));
-    temp[min(outlen-1, part4-part3)] = 0;
+    memset(temp, 0, std::min(outlen, num_bytes));
```
Comment (kadler) [inline db2i_file.cc]:
```suggestion
```

This isn't needed since we're going to overwrite it anyway.

File: db2i_file.cc [hunk 9]
```diff
@@ -387,9 +387,10 @@ void db2i_table::filenameToTablename(const char* in, char* out, size_t outlen)
...
+    size_t num_bytes2 = std::min(outlen, static_cast<size_t>(part4-part3));
+    memcpy(temp, part3, std::min(outlen, num_bytes2));
+    temp[std::min(static_cast<size_t>(outlen-1), num_bytes2)] = 0;
```
Comment (kadler) [inline db2i_file.cc]: Same as above. Also, we never use num_bytes from above again, so we could re-use it here instead of making num_bytes2.

Might be worth wrapping this code in to a function / lambda which can be called. Essentially what's being done is similar to strlcpy, eg.

```c++
// like strclpy, but takes srclen parameter too
auto strlcpy2 = [](char* dst, size_t size, const char* src, size_t srclen) {
  size = std::min(size-1, srclen);
  memcpy(dst, src, size);
  dst[size] = 0;
  return srclen;
}
```

That way we don't need the num_bytes variable around at all and the callsite is simplified to:

```c++
strlcpy2(tmp, outlen, part3, part4-part3);
```

Of course, as I look further, the only reason we are doing this copy in the first place is to extract a substring from `in` that is null-terminated so we can pass that string to `smartFilenameToTableName`. If `smartFilenameToTableName` took a "source length" parameter (instead of just assuming null-termination), we wouldn't even need to make any copies at all and most of this code would go away.

Maybe something like:

```c++

size_t db2i_table::smartFilenameToTableName(const char *in, size_t inlen, char* out, size_t outlen) {
 // copy old code here and adjust, using inlen
}

size_t db2i_table::smartFilenameToTableName(const char *in, char* out, size_t outlen) {
  return smartFilenameToTableName(in, strlen(in), out, outlen);
}
...

accumLen += smartFilenameToTableName(part3, part4-part3, &out[accumLen], outlen-accumLen);

```

Of course, now I'm really off in to the weeds for this change.

Comment (kadler) [reply db2i_file.cc]: We talked about this yesterday, the simplest "fix" for this is to just wrap these in a new scope:
```c++
{
  size_t num_bytes = std::min(outlen, static_cast<size_t>(part2 - part1));
  memcpy(temp, part1, std::min(outlen, num_bytes));
  temp[std::min(outlen-1, num_bytes)] = 0;
}
```

This way num_bytes cannot be used outside the scope and we can re-use the num_bytes name for each without contents of the variable accidentally affecting something else.

Comment (abmusse) [reply db2i_file.cc]: Updated

**Review by kadler — APPROVED** [review]
